# This Dockerfile builds the MariaDB container.
# It contains instructions for building the Docker Image.
# It installs the mariadb-server.

FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y

